"use server"

import { generateText } from "ai"
import { openai } from "@ai-sdk/openai"

export async function generateContent(prompt: string, contentType: string, tone: string): Promise<string> {
  try {
    // In a real implementation, you would use your OpenAI API key
    // This is a mock implementation for demonstration purposes
    if (!process.env.OPENAI_API_KEY) {
      // For demo purposes, return mock content
      return getMockContent(prompt, contentType, tone)
    }

    const systemPrompt = getSystemPrompt(contentType, tone)

    const { text } = await generateText({
      model: openai("gpt-4o"),
      system: systemPrompt,
      prompt: prompt,
    })

    return text
  } catch (error) {
    console.error("Error generating content:", error)
    throw new Error("Failed to generate content. Please try again.")
  }
}

function getSystemPrompt(contentType: string, tone: string): string {
  let systemPrompt = `You are ContentGenius, an expert AI content creator. Generate high-quality content in a ${tone} tone.`

  switch (contentType) {
    case "blog":
      systemPrompt +=
        " Create a well-structured blog post with a compelling title, introduction, main points with subheadings, and conclusion."
      break
    case "social":
      systemPrompt +=
        " Create engaging social media content that is concise, attention-grabbing, and includes relevant hashtags."
      break
    case "marketing":
      systemPrompt +=
        " Create persuasive marketing copy that highlights benefits, addresses pain points, and includes a clear call to action."
      break
    default:
      systemPrompt += " Create well-structured, engaging content based on the user's request."
  }

  return systemPrompt
}

// Mock function for demonstration purposes
function getMockContent(prompt: string, contentType: string, tone: string): string {
  // This is just for demonstration when no API key is available
  const mockResponses = {
    blog: `# The Ultimate Guide to Productivity Hacks

## Introduction
In today's fast-paced world, maximizing productivity has become more important than ever. Whether you're a student, professional, or entrepreneur, finding ways to get more done in less time can significantly impact your success and well-being.

## What is Productivity?
Productivity isn't just about doing more—it's about achieving meaningful results with less effort and stress. It's the balance between efficiency and effectiveness.

## Top Productivity Techniques
1. **The Pomodoro Technique**: Work in focused 25-minute intervals with short breaks in between.
2. **Time Blocking**: Schedule specific blocks of time for different tasks or projects.
3. **The 2-Minute Rule**: If a task takes less than 2 minutes, do it immediately.

## Tools to Boost Your Productivity
- Task management apps like Todoist or Asana
- Time tracking software like Toggl
- Focus apps like Forest or Freedom

## Conclusion
Implementing even a few of these productivity hacks can transform your workflow and help you achieve more of what matters most to you.`,

    social: `✨ Unlock your full potential with these game-changing productivity hacks! 💪

The secret to getting more done isn't working harder—it's working smarter.

Try these today:
• The Pomodoro Technique (25 min work + 5 min break)
• Time blocking your calendar
• The 2-minute rule for small tasks

Which one will you try first? Comment below! 👇

#ProductivityTips #WorkSmarter #LifeHacks #TimeManagement`,

    marketing: `**DOUBLE YOUR PRODUCTIVITY IN HALF THE TIME**

Are you tired of ending each day feeling like you've accomplished nothing?

Introducing our **Ultimate Productivity Masterclass** – the proven system that has helped over 10,000 professionals reclaim their time and skyrocket their results.

✅ Learn the exact techniques used by top performers
✅ Discover how to eliminate distractions permanently
✅ Master the art of deep work and flow states

"I've gained back 2 hours every day since implementing these strategies!" - Sarah K.

**Limited Time Offer: Get 30% off when you enroll before Friday.**

→ CLICK HERE TO TRANSFORM YOUR PRODUCTIVITY TODAY ←`,
  }

  return (
    mockResponses[contentType as keyof typeof mockResponses] ||
    "This is a placeholder for generated content. In a real implementation, this would be generated by an AI model based on your prompt."
  )
}
